# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45bec0545330fe736460eccb70822e350090f817c55b4320973c71bc6c2b010406364df0acd8b972695643ff6015f63c8da4dbdc2b43c483a4455640c9c49aaf

test:
  secret_key_base: 06a11a65c645eda362f6d7a3d5edd56a44ccf734dd7f7eb9a4c8e1b42908d49dfee3685208c2e14303b4b279d3744bd7ec055f51a6f1038f18b4eb2b07ece2ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
